// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcp-puHNxTCKnZwoZQrewJtv1g_Hi3c1I',
    appId: '1:532752999780:web:2eca2bcb8f650d16e80671',
    messagingSenderId: '532752999780',
    projectId: 'biowatch-c28c5',
    authDomain: 'biowatch-c28c5.firebaseapp.com',
    storageBucket: 'biowatch-c28c5.appspot.com',
    measurementId: 'G-1MQMNF5E72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeesHaz6rzV0csaXHZTzrsKM18uM0FQqk',
    appId: '1:532752999780:android:55ec6c2059b156f5e80671',
    messagingSenderId: '532752999780',
    projectId: 'biowatch-c28c5',
    storageBucket: 'biowatch-c28c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxdqOO5IvRlD61iWx0hWsnRIHGY_Sb_EM',
    appId: '1:532752999780:ios:93cee139fe088a27e80671',
    messagingSenderId: '532752999780',
    projectId: 'biowatch-c28c5',
    storageBucket: 'biowatch-c28c5.appspot.com',
    iosBundleId: 'com.example.wasteAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxdqOO5IvRlD61iWx0hWsnRIHGY_Sb_EM',
    appId: '1:532752999780:ios:f6b5d97fcf3942b1e80671',
    messagingSenderId: '532752999780',
    projectId: 'biowatch-c28c5',
    storageBucket: 'biowatch-c28c5.appspot.com',
    iosBundleId: 'com.example.wasteAi.RunnerTests',
  );
}
