name: waste_ai
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  image_picker: ^0.8.5+3
  http: ^0.13.3
  provider: ^6.0.2
  font_awesome_flutter: ^10.1.0
  google_maps_flutter: ^2.1.1
  cloud_firestore:
  firebase_auth: 
  firebase_storage:
  geolocator:
  image:
  url_launcher: 
  fl_chart: ^0.66.2
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/fire-icon-in-gradient-red-colors-flame-signs-illustration-png.webp
